version: '3'
networks:
  template-wordpress-net:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: template-wordpress-mysql
    tty: true
    ports:
      - 4208:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: name_database
      MYSQL_USER: many
      MYSQL_PASSWORD: 1234
    networks:
      - template-wordpress-net
  
  server:
    image: wordpress:latest
    container_name: template-wordpress
    ports:
      - 4282:80
    volumes:
      - server:/var/www/html
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: name_database
      WORDPRESS_DB_HOST: template-wordpress-mysql
    depends_on:
      - mysql
    networks:
      - template-wordpress-net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: template-phpmyadmin
    ports:
      - 4283:80
    environment:
     PMA_HOST: template-wordpress-mysql
     MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - template-wordpress-net

volumes:
  mysql:
  server:

